name: Methods Workshop
url: http://example.org
description: Columbia University | Department of Political Science

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
